# Generated by Django 5.0.4 on 2024-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_bugreport_task_featurerequest_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Наивысший'), (4, 'Высокий'), (3, 'Обычный'), (2, 'Ниже среднего'), (1, 'Несущественный')], default=0),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Наивысший'), (4, 'Высокий'), (3, 'Обычный'), (2, 'Ниже среднего'), (1, 'Несущественный')], default=0),
        ),
    ]
